---
framework: jest
preRun:
  command:
    - yarn
preMerge:
  env:
    TRACE_PLAYWRIGHT: true
    HEADLESS: true
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
postMerge:
  env:
    TRACE_PLAYWRIGHT: true
    HEADLESS: true
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
postRun:
  command:
    - node --version
version: 1.0

